
(() => {
const Q=window.PASSAR_QUESTIONS||[];
const STORE='passar-no-enem-v1';
const nodes=[
['mat.operacoes','Operações','FUNDACAO','base numérica'],['mat.fracoes','Frações','PONTE','parte, quociente e razão'],['mat.razao','Razão','PONTE','comparação multiplicativa'],['mat.proporcao','Proporção','NUCLEO','equivalência entre razões'],['mat.porcentagem','Porcentagem','NUCLEO','percentuais e variações'],['mat.regra3','Regra de três','APLICACAO','proporcionalidade'],['mat.unidades','Unidades e conversões','PONTE','grandezas e medidas'],['mat.escala','Escalas','NUCLEO','representação proporcional'],['mat.area','Áreas','NUCLEO','superfícies'],['mat.volume','Volumes','NUCLEO','espaço'],['mat.graficos','Leitura de gráficos','TRANSVERSAL','representação quantitativa'],['mat.tabelas','Leitura de tabelas','TRANSVERSAL','dados'],['mat.media','Média','NUCLEO','tendência central'],['mat.probabilidade','Probabilidade','NUCLEO','incerteza'],['mat.algebra','Álgebra básica','PONTE','variáveis'],['mat.equacoes','Equações','NUCLEO','modelagem'],['mat.funcoes','Funções','NUCLEO','dependência']
];
const prereq=[['mat.operacoes','mat.fracoes'],['mat.fracoes','mat.razao'],['mat.razao','mat.proporcao'],['mat.fracoes','mat.porcentagem'],['mat.razao','mat.porcentagem'],['mat.razao','mat.regra3'],['mat.proporcao','mat.regra3'],['mat.operacoes','mat.unidades'],['mat.proporcao','mat.escala'],['mat.unidades','mat.escala'],['mat.unidades','mat.area'],['mat.unidades','mat.volume'],['mat.operacoes','mat.graficos'],['mat.operacoes','mat.tabelas'],['mat.operacoes','mat.media'],['mat.tabelas','mat.media'],['mat.fracoes','mat.probabilidade'],['mat.operacoes','mat.probabilidade'],['mat.operacoes','mat.algebra'],['mat.algebra','mat.equacoes'],['mat.algebra','mat.funcoes'],['mat.graficos','mat.funcoes']];
const topicToNode={
'Porcentagem':'mat.porcentagem','Porcentagem e custos':'mat.porcentagem','Porcentagem e preços':'mat.porcentagem','Razão':'mat.razao','Razão e proporcionalidade':'mat.razao','Razão e tempo':'mat.razao','Proporcionalidade':'mat.proporcao','Escalas':'mat.escala','Escalas e semelhança':'mat.escala','Grandezas e medidas':'mat.unidades','Estatística':'mat.media','Estatística e probabilidade':'mat.probabilidade','Probabilidade':'mat.probabilidade','Princípios de contagem':'mat.operacoes','Geometria espacial':'mat.volume','Geometria plana':'mat.area','Geometria analítica':'mat.algebra','Funções':'mat.funcoes','Funções logarítmicas':'mat.funcoes','Modelagem algébrica':'mat.algebra','Matemática financeira':'mat.algebra','Localização e movimentação':'mat.graficos','Estatística e leitura de gráficos':'mat.graficos','Estatística e gráficos':'mat.graficos','Leitura de gráficos':'mat.graficos','Relações entre grandezas':'mat.proporcao'};
let state=load(); let route='home'; let selectedQ=null; let filter='all'; let search='';
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{attempts:{},streak:0,seen:0}}catch{return {attempts:{},streak:0,seen:0}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pct(v){return Math.round(v*100)}
function stats(){const vals=Object.values(state.attempts); const answered=vals.length; const correct=vals.reduce((a,x)=>a+(x.correct?1:0),0); const totalAttempts=vals.reduce((a,x)=>a+x.count,0); const wrong=totalAttempts-correct; return {answered,correct,totalAttempts,wrong,accuracy:totalAttempts?pct(correct/totalAttempts):0}}
function topicStats(){const map={}; Q.forEach(q=>{const t=q.topic||'Outros'; if(!map[t])map[t]={total:0,answered:0,correct:0};map[t].total++;const a=state.attempts[q.id];if(a){map[t].answered++;map[t].correct+=a.correct?1:0}});return map}
function mission(){
 const arr=Q.filter(q=>!q.annulled).map(q=>{const a=state.attempts[q.id];const node=topicToNode[q.topic];let score=0,reason='Ainda não estudada';if(!a){score+=100}else{score+=(a.correct?15:80);reason=a.correct?'Reforço de fluência':'Retorno após erro'};if(node==='mat.operacoes')score+=12;if(q.topic==='Porcentagem')score+=8;return {...q,score,reason}});return arr.sort((a,b)=>b.score-a.score||a.id-b.id).slice(0,5)
}
function layout(content){document.querySelector('#app').innerHTML=`<div class="shell"><header class="top"><div class="topin"><div class="brand"><span class="brandmark">N</span><span>PASSAR NO ENEM</span></div><nav class="nav"><button class="${route==='home'?'active':''}" onclick="go('home')">Minha Direção</button><button class="${route==='estudo'?'active':''}" onclick="go('estudo')">Estudar</button><button class="${route==='palacio'?'active':''}" onclick="go('palacio')">Palácio do Conhecimento</button><button class="${route==='progresso'?'active':''}" onclick="go('progresso')">Meu progresso</button></nav><div class="topstat">${stats().answered}/45 questões</div></div></header><main class="content">${content}</main><div class="footer">PASSAR NO ENEM · modo local de estudo · seus registros ficam neste navegador.</div></div>`}
function home(){const s=stats(), m=mission();layout(`<section class="hero"><div class="panel heroMain"><div class="eyebrow">Direção · prática · evolução</div><h1>Estude com direção.<br>Não apenas com conteúdo.</h1><p>Comece pelo que mais importa agora. O site registra suas tentativas, identifica fragilidades e reorganiza sua prática sem bloquear sua liberdade de estudar.</p><div class="actions"><button class="btn primary" onclick="go('missao')">Começar minha missão</button><button class="btn" onclick="go('estudo')">Escolher uma questão</button></div></div><div class="panel heroSide"><div class="eyebrow">Seu estado agora</div><div class="kpi"><span>Questões respondidas</span><strong>${s.answered}</strong></div><div class="kpi"><span>Acerto nas tentativas</span><strong>${s.accuracy}%</strong></div><div class="kpi"><span>Erros para investigar</span><strong>${s.wrong}</strong></div><div class="kpi"><span>Questões disponíveis</span><strong>${Q.filter(q=>!q.annulled).length}</strong></div></div></section><div class="grid"><div class="panel card"><h3>1 · Descobrir</h3><p class="muted">Você não precisa saber antecipadamente qual conteúdo usar. Leia o problema, identifique as grandezas e tente.</p></div><div class="panel card"><h3>2 · Pensar</h3><p class="muted">A resposta não aparece antes da sua tentativa. Depois, registre o tipo de dificuldade que realmente aconteceu.</p></div><div class="panel card"><h3>3 · Consolidar</h3><p class="muted">Erros voltam para sua direção. Acertos continuam sendo acompanhados para evitar falsa sensação de domínio.</p></div></div><div class="sectionTitle"><h2>Próximo passo</h2><span class="pill yellow">5 itens selecionados</span></div><div class="panel card"><div class="missionList">${m.map(item=>missionRow(item)).join('')}</div></div>`)}
function missionRow(q){return `<div class="missionItem"><div><div class="qnum">QUESTÃO ${q.id}</div><div class="topic">${esc(q.topic||'Matemática')}</div><div class="reason">${esc(q.reason)} · ${esc(q.subtopic||'')}</div></div><button class="btn blue" onclick="openQ(${q.id},'missao')">Estudar</button></div>`}
function missionPage(){const m=mission();layout(`<div class="back"><button class="ghost" onclick="go('home')">← Minha Direção</button></div><div class="sectionTitle"><div><div class="eyebrow">Missão de hoje</div><h2 style="font-size:32px;margin:8px 0 0">Cinco questões, uma direção</h2><p class="muted">Prioridade determinística: primeiro o que ainda não foi visto; depois, o que apresentou fragilidade.</p></div><span class="pill yellow">${m.length} itens</span></div><div class="panel card"><div class="missionList">${m.map(missionRow).join('')}</div></div>`)}
function study(){const filtered=Q.filter(q=>{if(q.annulled&&filter!=='annulled')return false;if(filter==='unseen'&&state.attempts[q.id])return false;if(filter==='wrong'&&(!state.attempts[q.id]||state.attempts[q.id].correct))return false;if(filter==='answered'&&!state.attempts[q.id])return false;const hay=(q.prompt+' '+(q.topic||'')+' '+(q.subtopic||'')+' '+q.id).toLowerCase();return !search||hay.includes(search.toLowerCase())});layout(`<div class="sectionTitle"><div><div class="eyebrow">Prática oficial</div><h2 style="font-size:32px;margin:8px 0 0">Estudar Matemática</h2><p class="muted">Questões do ENEM 2025, Caderno Azul, questões 136–180. Questões anuladas não entram no desempenho.</p></div></div><div class="filters"><input class="input" placeholder="Buscar questão, conteúdo..." value="${esc(search)}" oninput="setSearch(this.value)"><button class="btn ${filter==='all'?'blue':''}" onclick="setFilter('all')">Todas</button><button class="btn ${filter==='unseen'?'blue':''}" onclick="setFilter('unseen')">Não estudadas</button><button class="btn ${filter==='wrong'?'blue':''}" onclick="setFilter('wrong')">Errei</button><button class="btn ${filter==='answered'?'blue':''}" onclick="setFilter('answered')">Respondidas</button><button class="btn ${filter==='annulled'?'blue':''}" onclick="setFilter('annulled')">Anulada</button></div><div class="panel card"><table class="table"><thead><tr><th>Questão</th><th>Conteúdo</th><th>Estado</th><th></th></tr></thead><tbody>${filtered.map(q=>{const a=state.attempts[q.id];return `<tr><td><strong>${q.id}</strong></td><td>${esc(q.topic||'Matemática')}<div class="small muted">${esc(q.subtopic||'')}</div></td><td>${q.annulled?'<span class="pill red">ANULADA</span>':a?(a.correct?'<span class="pill green">acerto</span>':'<span class="pill red">erro</span>'):'<span class="pill">nova</span>'}</td><td><button class="btn" onclick="openQ(${q.id},'estudo')">Abrir</button></td></tr>`}).join('')}</tbody></table>${filtered.length===0?'<div class="empty">Nada encontrado com esses filtros.</div>':''}</div>`)}
function openQ(id,from){selectedQ=Q.find(q=>q.id===id);route='questao';layout(questionHTML(selectedQ,from));}
function questionHTML(q,from){const a=state.attempts[q.id];const answered=!!a;const options=Object.entries(q.options||{}).filter(([k,v])=>v||['A','B','C','D','E'].every(x=>q.options[x]!==''));return `<div class="back"><button class="ghost" onclick="go('${from==='missao'?'missao':'estudo'}')">← Voltar</button></div><section class="panel question"><div class="questionHead"><div><div class="qnum">ENEM 2025 · QUESTÃO ${q.id}</div><div class="questionTitle">${esc(q.topic||'Matemática')} <span class="pill">${esc(q.subtopic||'')}</span></div></div><div class="pill ${q.annulled?'red':'yellow'}">${q.annulled?'ANULADA':'OFICIAL'}</div></div><div class="prompt">${esc(q.prompt)}</div>${q.page?`<div class="small muted">Caderno Azul · página ${q.page}. <button class="link" onclick="showSource(${q.page})">Ver referência da prova</button></div>`:''}${q.annulled?'<div class="feedback"><strong>Questão anulada.</strong><p class="muted">Ela pode ser estudada, mas não altera seu desempenho.</p></div>':`<div class="options">${Object.entries(q.options).map(([l,v])=>`<button class="option ${a&&a.answer===l?(a.correct?'correct':'wrong'):(a&&a.revealed&&q.answer===l?'correct':'')}" onclick="answerQ('${l}')"><span class="letter">${l}</span><span>${esc(v||'Alternativa visual — consulte a página da prova')}</span></button>`).join('')}</div>${a&&a.revealed?feedback(q,a):'<div class="feedback"><strong>Antes de responder:</strong> qual é a relação entre as informações do enunciado e o que a questão pede?</div>'}`}</section>`}
function feedback(q,a){return `<div class="feedback ${a.correct?'good':'bad'}"><strong>${a.correct?'Você acertou.':'Você errou — agora investigue o erro.'}</strong><p>${a.correct?'Resposta registrada como evidência local de acerto.':'Não trate o erro como diagnóstico definitivo. Escolha uma hipótese abaixo.'} ${q.answer?`Gabarito: <strong>${q.answer}</strong>.`:''}</p>${!a.correct?`<div class="diagnosis">${['Conceito','Interpretação','Cálculo','Estratégia','Atenção','Pré-requisito'].map(d=>`<button class="diagBtn ${a.diagnosis===d?'active':''}" onclick="diag('${d}')">${d}</button>`).join('')}</div>`:''}<div class="actions"><button class="btn blue" onclick="go('estudo')">Próxima questão</button><button class="btn" onclick="showWhy(${q.id})">O que essa questão treina?</button></div></div>`}
function answerQ(letter){if(!selectedQ||selectedQ.annulled)return;const prev=state.attempts[selectedQ.id]||{count:0};const correct=letter===selectedQ.answer;state.attempts[selectedQ.id]={...prev,answer:letter,correct,revealed:true,count:prev.count+1,last:Date.now()};save();renderCurrent()}
function diag(d){if(!selectedQ)return;state.attempts[selectedQ.id].diagnosis=d;save();renderCurrent()}
function renderCurrent(){if(route==='questao'&&selectedQ){document.querySelector('#app').innerHTML='';questionHTML(selectedQ,'estudo');layout(questionHTML(selectedQ,'estudo'))}}
function showWhy(id){const q=Q.find(x=>x.id===id);if(!q)return;const node=topicToNode[q.topic];document.body.insertAdjacentHTML('beforeend',`<div class="modalShade" id="modal"><div class="panel modal"><button class="close" onclick="document.querySelector('#modal').remove()">×</button><div class="eyebrow">Laboratório Mental</div><h2>${esc(q.topic||'Matemática')}</h2><p class="muted">A habilidade principal desta questão foi classificada como <strong>${esc(q.skill||'não informado')}</strong>.</p><p><strong>Subconteúdo:</strong> ${esc(q.subtopic||'—')}</p><p><strong>Dimensão cognitiva:</strong> ${esc(q.dimension||'—')}</p><p><strong>Ligação no Palácio:</strong> ${esc(node||'ainda sem nó pedagógico liberado')}</p><hr style="border-color:var(--line);border-width:1px 0 0;margin:18px 0"><p class="muted">Antes de olhar uma fórmula, pergunte: <em>o que varia? o que permanece? qual unidade? qual relação transforma os dados em resposta?</em></p></div></div>`)}
function showSource(page){window.open('assets/prova-2025-caderno-azul-2dia.pdf#page='+page,'_blank','noopener')}
function palace(){const ns=nodes.map(n=>{const a=Object.values(state.attempts).filter(x=>x.node===n[0]).length;return `<button class="node ${n[2].toLowerCase()}" onclick="nodeInfo('${n[0]}')"><strong>${n[1]}</strong><small>${n[3]}</small><small>${a?'evidências locais: '+a:'ainda sem evidência'}</small></button>`}).join('');layout(`<div class="sectionTitle"><div><div class="eyebrow">Navegação livre</div><h2 style="font-size:32px;margin:8px 0 0">Palácio do Conhecimento</h2><p class="muted">A estrutura mostra pré-requisitos e relações; ela não bloqueia seu acesso às questões.</p></div></div><div class="panel card"><div class="nodeGrid">${ns}</div></div><div class="sectionTitle"><h2>Algumas relações fundamentais</h2></div><div class="panel card"><table class="table"><thead><tr><th>Pré-requisito</th><th>Abre caminho para</th></tr></thead><tbody>${prereq.map(([a,b])=>`<tr><td>${nodes.find(n=>n[0]===a)?.[1]||a}</td><td>${nodes.find(n=>n[0]===b)?.[1]||b}</td></tr>`).join('')}</tbody></table></div>`)}
function nodeInfo(id){const n=nodes.find(x=>x[0]===id);const next=prereq.filter(x=>x[0]===id).map(x=>nodes.find(y=>y[0]===x[1])?.[1]);const prev=prereq.filter(x=>x[1]===id).map(x=>nodes.find(y=>y[0]===x[0])?.[1]);document.body.insertAdjacentHTML('beforeend',`<div class="modalShade" id="modal"><div class="panel modal"><button class="close" onclick="document.querySelector('#modal').remove()">×</button><div class="eyebrow">Nó pedagógico</div><h2>${n[1]}</h2><p class="muted">${n[3]}</p><p><strong>Antes:</strong> ${prev.length?prev.join(', '):'fundação'}</p><p><strong>Conecta com:</strong> ${next.length?next.join(', '):'—'}</p><button class="btn primary" onclick="go('estudo');document.querySelector('#modal')?.remove()">Praticar</button></div></div>`)}
function progress(){const s=stats(),ts=topicStats();const rows=Object.entries(ts).sort((a,b)=>(b[1].answered?b[1].correct/b[1].answered:0)-(a[1].answered?a[1].correct/a[1].answered:0)).map(([t,v])=>{const rate=v.answered?Math.round(v.correct/v.answered*100):0;return `<tr><td><strong>${esc(t)}</strong></td><td>${v.answered}/${v.total}</td><td>${v.answered?rate+'%':'—'}</td><td><div class="bar"><i style="width:${v.answered?rate:0}%"></i></div></td></tr>`}).join('');layout(`<div class="sectionTitle"><div><div class="eyebrow">Evolução</div><h2 style="font-size:32px;margin:8px 0 0">Meu progresso</h2></div></div><div class="grid"><div class="panel card"><span class="muted">Respondidas</span><h2>${s.answered}</h2><div class="bar"><i style="width:${s.answered/Q.length*100}%"></i></div></div><div class="panel card"><span class="muted">Acerto</span><h2>${s.accuracy}%</h2><div class="bar"><i style="width:${s.accuracy}%"></i></div></div><div class="panel card"><span class="muted">Erros registrados</span><h2>${s.wrong}</h2><p class="muted">Erro é hipótese para investigação, não rótulo.</p></div></div><div class="sectionTitle"><h2>Por conteúdo</h2></div><div class="panel card"><table class="table"><thead><tr><th>Conteúdo</th><th>Respondidas</th><th>Acerto</th><th>Domínio observado</th></tr></thead><tbody>${rows}</tbody></table></div><div class="sectionTitle"><h2>Erros a investigar</h2></div><div class="panel card">${Object.entries(state.attempts).filter(([id,a])=>!a.correct).map(([id,a])=>{const q=Q.find(x=>x.id==id);return `<div class="missionItem"><div><div class="qnum">QUESTÃO ${id}</div><div class="topic">${esc(q?.topic||'')}</div><div class="reason">Hipótese: ${esc(a.diagnosis||'ainda não classificada')}</div></div><button class="btn" onclick="openQ(${id},'progresso')">Reinvestigar</button></div>`}).join('')||'<div class="empty">Nenhum erro registrado ainda. Continue praticando.</div>'}</div>`)}
function go(r){route=r;selectedQ=null;if(r==='home')home();else if(r==='missao')missionPage();else if(r==='estudo')study();else if(r==='palacio')palace();else if(r==='progresso')progress()}
function setFilter(v){filter=v;study()} function setSearch(v){search=v;study()} window.go=go;window.openQ=openQ;window.answerQ=answerQ;window.diag=diag;window.showWhy=showWhy;window.showSource=showSource;window.nodeInfo=nodeInfo;window.setFilter=setFilter;window.setSearch=setSearch;
home();
})();
